/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sdu.lecture.secim;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Scanner;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpringLayout;

/**
 *
 * @author ecirk
 */
public class NewJFrame extends javax.swing.JFrame {

    List<Il> iller = new ArrayList<>();
    List<Ilce> ilceler = new ArrayList<>();

    public NewJFrame() {
        try {
            initComponents();
            //cmb_il dolduruluyor
            String path = System.getProperty("user.dir") + "/resources/il.csv";
            File file = new File(path);
            Scanner myReader = new Scanner(file);

            cmb_il.setRenderer(new ItemRenderer());
            while (myReader.hasNextLine()) {

                String[] ss = myReader.nextLine().split(",");
                iller.add(new Il(Integer.parseInt(ss[0]), ss[1]));
            }

            iller.sort(Comparator.comparingInt(Il::getId));

            DefaultComboBoxModel<Il> ilModel = new DefaultComboBoxModel<>();
            ilModel.addAll(iller);
            cmb_il.setModel(ilModel);

            // ilceler dolduruluyoe
            path = System.getProperty("user.dir") + "/resources/ilce.csv";
            file = new File(path);
            myReader = new Scanner(file);
            while (myReader.hasNextLine()) {

                String[] ss = myReader.nextLine().split(",");
                ilceler.add(new Ilce(Integer.parseInt(ss[0]), ss[1]));
            }

        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_il = new javax.swing.JComboBox<>();
        cmb_ilce = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmb_il.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cmb_il, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(cmb_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_il, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ilce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(375, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Iterable<Ilce> filterById(int id) {
        return ilceler.
                stream().
                filter(x -> x.getIlId() == id)
                .collect(Collectors.toList());
    }


    private void cmb_ilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ilActionPerformed
        
        cmb_ilce.setRenderer(new IlceRenderer());
        
        Il seletedCity = (Il) cmb_il.getSelectedItem();

        Iterable<Ilce> selectedTowns = filterById(seletedCity.getId());

        DefaultComboBoxModel<Ilce> ilceModel = new DefaultComboBoxModel<>();
        ilceModel.addAll(StreamSupport.stream(selectedTowns.spliterator(),false)
        .collect(Collectors.toList()));
    
        cmb_ilce.setModel(ilceModel);


    }//GEN-LAST:event_cmb_ilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Il> cmb_il;
    private javax.swing.JComboBox<Ilce> cmb_ilce;
    // End of variables declaration//GEN-END:variables
}
